- name: Set up Android SDK
  uses: android-actions/setup-android@v3
  with:
    accept-android-sdk-licenses: true
    packages: |
      platforms;android-34
      build-tools;34.0.0
      platform-tools- name: Set up Android SDK
  uses: android-actions/setup-android@v3
  with:
    accept-android-sdk-licenses: true
    packages: |
      platforms;android-34
      build-tools;34.0.0
      platform-tools- name: Set up Android SDK
  uses: android-actions/setup-android@v3
  with:
    accept-android-sdk-licenses: true
    packages: |
      platforms;android-34
      build-tools;34.0.0
      platform-tools
