name: Android CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          cmdline-tools-version: 'latest'
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools
      - name: List available SDK packages
        run: /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --list --verbose
      - name: Install SDK packages
        run: |
          /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"
