name: Android CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools
      - name: List SDK packages
        run: /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --list
      - name: Install SDK packages
        run: |
          /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"
